// Generated by scripts/build_idl.py. Do not edit.
export type Segments = {
  "address": "6PHe3DsZvs3JdYzELQSQ9hK6ReYqTYPc9rspXBKkf1rh",
  "metadata": {
    "name": "segments",
    "version": "0.1.0",
    "spec": "0.1.0",
    "description": "Split a tokenized stock into fixed segment tokens and back"
  },
  "instructions": [
    {
      "name": "initConfig",
      "discriminator": [
        23,
        235,
        115,
        232,
        168,
        96,
        1,
        231
      ],
      "accounts": [
        {
          "name": "payer",
          "writable": true,
          "signer": true
        },
        {
          "name": "config",
          "writable": true
        },
        {
          "name": "programData",
          "docs": [
            "Only the program's upgrade authority may initialise, so nobody can front-run the deploy."
          ]
        },
        {
          "name": "systemProgram"
        }
      ],
      "args": [
        {
          "name": "admin",
          "type": "pubkey"
        },
        {
          "name": "guardian",
          "type": "pubkey"
        },
        {
          "name": "treasury",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "proposeAdmin",
      "discriminator": [
        121,
        214,
        199,
        212,
        87,
        39,
        117,
        234
      ],
      "accounts": [
        {
          "name": "admin",
          "signer": true
        },
        {
          "name": "config",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "newAdmin",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "acceptAdmin",
      "discriminator": [
        112,
        42,
        45,
        90,
        116,
        181,
        13,
        170
      ],
      "accounts": [
        {
          "name": "newAdmin",
          "signer": true
        },
        {
          "name": "config",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "setGuardian",
      "discriminator": [
        147,
        243,
        50,
        121,
        154,
        164,
        50,
        30
      ],
      "accounts": [
        {
          "name": "admin",
          "signer": true
        },
        {
          "name": "config",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "guardian",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "setTreasury",
      "discriminator": [
        57,
        97,
        196,
        95,
        195,
        206,
        106,
        136
      ],
      "accounts": [
        {
          "name": "admin",
          "signer": true
        },
        {
          "name": "config",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "treasury",
          "type": "pubkey"
        }
      ]
    },
    {
      "name": "createSeries",
      "discriminator": [
        181,
        9,
        52,
        120,
        197,
        221,
        42,
        142
      ],
      "accounts": [
        {
          "name": "admin",
          "writable": true,
          "signer": true
        },
        {
          "name": "config"
        },
        {
          "name": "underlyingMint"
        },
        {
          "name": "series",
          "writable": true
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "underlyingTokenProgram"
        },
        {
          "name": "systemProgram"
        }
      ],
      "args": [
        {
          "name": "seriesId",
          "type": "u16"
        },
        {
          "name": "metadataUri",
          "type": "string"
        }
      ]
    },
    {
      "name": "addPartial",
      "discriminator": [
        60,
        181,
        8,
        163,
        232,
        74,
        63,
        247
      ],
      "accounts": [
        {
          "name": "admin",
          "writable": true,
          "signer": true
        },
        {
          "name": "config"
        },
        {
          "name": "series",
          "writable": true
        },
        {
          "name": "partialMint",
          "docs": [
            "Token-2022 mint whose mint authority is the series PDA forever, with no freeze",
            "authority and no permanent delegate."
          ],
          "writable": true
        },
        {
          "name": "tokenProgram"
        },
        {
          "name": "systemProgram"
        }
      ],
      "args": [
        {
          "name": "weightBps",
          "type": "u16"
        },
        {
          "name": "name",
          "type": "string"
        },
        {
          "name": "symbol",
          "type": "string"
        },
        {
          "name": "uri",
          "type": "string"
        }
      ]
    },
    {
      "name": "finalizeSeries",
      "discriminator": [
        132,
        16,
        186,
        46,
        6,
        76,
        125,
        188
      ],
      "accounts": [
        {
          "name": "admin",
          "signer": true
        },
        {
          "name": "config"
        },
        {
          "name": "series",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "setSeriesUri",
      "discriminator": [
        47,
        204,
        156,
        243,
        138,
        52,
        159,
        123
      ],
      "accounts": [
        {
          "name": "admin",
          "signer": true
        },
        {
          "name": "config"
        },
        {
          "name": "series",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "metadataUri",
          "type": "string"
        }
      ]
    },
    {
      "name": "scheduleFee",
      "discriminator": [
        67,
        220,
        176,
        104,
        30,
        254,
        14,
        75
      ],
      "accounts": [
        {
          "name": "admin",
          "signer": true
        },
        {
          "name": "config"
        },
        {
          "name": "series",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "mintFeeBps",
          "type": "u16"
        },
        {
          "name": "redeemFeeBps",
          "type": "u16"
        }
      ]
    },
    {
      "name": "cancelFee",
      "discriminator": [
        5,
        77,
        56,
        64,
        104,
        252,
        30,
        22
      ],
      "accounts": [
        {
          "name": "admin",
          "signer": true
        },
        {
          "name": "config"
        },
        {
          "name": "series",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "applyFee",
      "discriminator": [
        59,
        156,
        222,
        176,
        105,
        28,
        247,
        64
      ],
      "accounts": [
        {
          "name": "series",
          "writable": true
        }
      ],
      "args": []
    },
    {
      "name": "setMintPaused",
      "discriminator": [
        122,
        112,
        56,
        49,
        172,
        101,
        49,
        228
      ],
      "accounts": [
        {
          "name": "authority",
          "signer": true
        },
        {
          "name": "config"
        },
        {
          "name": "series",
          "writable": true
        }
      ],
      "args": [
        {
          "name": "paused",
          "type": "bool"
        }
      ]
    },
    {
      "name": "sweepFees",
      "discriminator": [
        175,
        225,
        98,
        71,
        118,
        66,
        34,
        148
      ],
      "accounts": [
        {
          "name": "config"
        },
        {
          "name": "series",
          "writable": true
        },
        {
          "name": "underlyingMint"
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "treasuryAccount",
          "writable": true
        },
        {
          "name": "underlyingTokenProgram"
        }
      ],
      "args": []
    },
    {
      "name": "mintSet",
      "discriminator": [
        91,
        117,
        1,
        75,
        201,
        110,
        110,
        189
      ],
      "accounts": [
        {
          "name": "user",
          "signer": true
        },
        {
          "name": "series",
          "writable": true
        },
        {
          "name": "underlyingMint"
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "userUnderlying",
          "writable": true
        },
        {
          "name": "underlyingTokenProgram"
        },
        {
          "name": "tokenProgram"
        }
      ],
      "args": [
        {
          "name": "amount",
          "type": "u64"
        }
      ]
    },
    {
      "name": "redeemSet",
      "discriminator": [
        167,
        80,
        14,
        7,
        40,
        75,
        188,
        216
      ],
      "accounts": [
        {
          "name": "user",
          "signer": true
        },
        {
          "name": "series",
          "writable": true
        },
        {
          "name": "underlyingMint"
        },
        {
          "name": "vault",
          "writable": true
        },
        {
          "name": "userUnderlying",
          "writable": true
        },
        {
          "name": "underlyingTokenProgram"
        },
        {
          "name": "tokenProgram"
        }
      ],
      "args": [
        {
          "name": "sets",
          "type": "u64"
        }
      ]
    }
  ],
  "accounts": [
    {
      "name": "config",
      "discriminator": [
        155,
        12,
        170,
        224,
        30,
        250,
        204,
        130
      ]
    },
    {
      "name": "series",
      "discriminator": [
        240,
        97,
        8,
        183,
        139,
        77,
        250,
        162
      ]
    }
  ],
  "types": [
    {
      "name": "feeApplied",
      "type": {
        "fields": [
          {
            "name": "series",
            "type": "pubkey"
          },
          {
            "name": "mintFeeBps",
            "type": "u16"
          },
          {
            "name": "redeemFeeBps",
            "type": "u16"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "feeScheduled",
      "type": {
        "fields": [
          {
            "name": "series",
            "type": "pubkey"
          },
          {
            "name": "mintFeeBps",
            "type": "u16"
          },
          {
            "name": "redeemFeeBps",
            "type": "u16"
          },
          {
            "name": "effectiveAt",
            "type": "i64"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "mintPauseChanged",
      "type": {
        "fields": [
          {
            "name": "series",
            "type": "pubkey"
          },
          {
            "name": "paused",
            "type": "bool"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "seriesCreated",
      "type": {
        "fields": [
          {
            "name": "series",
            "type": "pubkey"
          },
          {
            "name": "underlyingMint",
            "type": "pubkey"
          },
          {
            "name": "seriesId",
            "type": "u16"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "seriesFinalized",
      "type": {
        "fields": [
          {
            "name": "series",
            "type": "pubkey"
          },
          {
            "name": "partialMints",
            "type": {
              "vec": "pubkey"
            }
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "setMinted",
      "type": {
        "fields": [
          {
            "name": "series",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "deposited",
            "type": "u64"
          },
          {
            "name": "fee",
            "type": "u64"
          },
          {
            "name": "sets",
            "type": "u64"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "setRedeemed",
      "type": {
        "fields": [
          {
            "name": "series",
            "type": "pubkey"
          },
          {
            "name": "user",
            "type": "pubkey"
          },
          {
            "name": "sets",
            "type": "u64"
          },
          {
            "name": "fee",
            "type": "u64"
          },
          {
            "name": "withdrawn",
            "type": "u64"
          }
        ],
        "kind": "struct"
      }
    },
    {
      "name": "config",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "admin",
            "docs": [
              "Creates series and schedules fees. Intended to be a Squads multisig."
            ],
            "type": "pubkey"
          },
          {
            "name": "pendingAdmin",
            "docs": [
              "Set by `propose_admin`, takes over on `accept_admin`."
            ],
            "type": {
              "option": "pubkey"
            }
          },
          {
            "name": "guardian",
            "docs": [
              "May pause and unpause minting. Has no power over redemption."
            ],
            "type": "pubkey"
          },
          {
            "name": "treasury",
            "docs": [
              "Owner of the token accounts that receive swept fees."
            ],
            "type": "pubkey"
          },
          {
            "name": "bump",
            "type": "u8"
          }
        ]
      }
    },
    {
      "name": "pendingFee",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "mintFeeBps",
            "type": "u16"
          },
          {
            "name": "redeemFeeBps",
            "type": "u16"
          },
          {
            "name": "effectiveAt",
            "type": "i64"
          }
        ]
      }
    },
    {
      "name": "series",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "underlyingMint",
            "type": "pubkey"
          },
          {
            "name": "underlyingTokenProgram",
            "type": "pubkey"
          },
          {
            "name": "underlyingDecimals",
            "type": "u8"
          },
          {
            "name": "vault",
            "type": "pubkey"
          },
          {
            "name": "seriesId",
            "type": "u16"
          },
          {
            "name": "partialCount",
            "docs": [
              "Number of partials. Fixed once `finalized` is true."
            ],
            "type": "u8"
          },
          {
            "name": "partialMints",
            "type": {
              "array": [
                "pubkey",
                8
              ]
            }
          },
          {
            "name": "weightsBps",
            "docs": [
              "Informational seed weights, sum to 10,000 once finalized. Not used in any math."
            ],
            "type": {
              "array": [
                "u16",
                8
              ]
            }
          },
          {
            "name": "finalized",
            "docs": [
              "Once true, the composition can never change. There is no instruction to unset it."
            ],
            "type": "bool"
          },
          {
            "name": "mintPaused",
            "type": "bool"
          },
          {
            "name": "mintFeeBps",
            "type": "u16"
          },
          {
            "name": "redeemFeeBps",
            "type": "u16"
          },
          {
            "name": "pendingFee",
            "type": {
              "option": {
                "defined": {
                  "name": "pendingFee"
                }
              }
            }
          },
          {
            "name": "outstandingSets",
            "docs": [
              "Complete sets in circulation. Every partial's supply equals this."
            ],
            "type": "u64"
          },
          {
            "name": "accruedFees",
            "docs": [
              "Fees held in the vault, waiting for `sweep_fees`."
            ],
            "type": "u64"
          },
          {
            "name": "metadataUri",
            "type": "string"
          },
          {
            "name": "createdAt",
            "type": "i64"
          },
          {
            "name": "bump",
            "type": "u8"
          },
          {
            "name": "vaultBump",
            "type": "u8"
          }
        ]
      }
    }
  ],
  "errors": [
    {
      "code": 6000,
      "name": "feeTooHigh",
      "msg": "Fee exceeds the hard cap"
    },
    {
      "code": 6001,
      "name": "noPendingFee",
      "msg": "No fee change is pending"
    },
    {
      "code": 6002,
      "name": "feeTimelockActive",
      "msg": "The fee timelock has not elapsed"
    },
    {
      "code": 6003,
      "name": "seriesFinalized",
      "msg": "Series is already finalized and cannot be changed"
    },
    {
      "code": 6004,
      "name": "seriesNotFinalized",
      "msg": "Series is not finalized yet"
    },
    {
      "code": 6005,
      "name": "tooManyPartials",
      "msg": "Series has too many partials"
    },
    {
      "code": 6006,
      "name": "tooFewPartials",
      "msg": "Series needs at least two partials"
    },
    {
      "code": 6007,
      "name": "badPartialIndex",
      "msg": "Partial index must equal the current partial count"
    },
    {
      "code": 6008,
      "name": "badWeights",
      "msg": "Partial weights must sum to 10,000 bps"
    },
    {
      "code": 6009,
      "name": "mintPaused",
      "msg": "Minting is paused for this series"
    },
    {
      "code": 6010,
      "name": "zeroAmount",
      "msg": "Amount must be greater than zero"
    },
    {
      "code": 6011,
      "name": "amountTooSmall",
      "msg": "Amount is too small to cover the fee"
    },
    {
      "code": 6012,
      "name": "wrongPartialAccounts",
      "msg": "Wrong number of partial accounts"
    },
    {
      "code": 6013,
      "name": "wrongPartialMint",
      "msg": "Partial mint does not match the series"
    },
    {
      "code": 6014,
      "name": "wrongTokenAccount",
      "msg": "Token account has the wrong mint or owner"
    },
    {
      "code": 6015,
      "name": "stringTooLong",
      "msg": "String is too long"
    },
    {
      "code": 6016,
      "name": "unauthorized",
      "msg": "Signer is not allowed to do this"
    },
    {
      "code": 6017,
      "name": "noPendingAdmin",
      "msg": "No admin transfer is pending"
    },
    {
      "code": 6018,
      "name": "mathOverflow",
      "msg": "Arithmetic overflow"
    }
  ],
  "events": [
    {
      "discriminator": [
        63,
        184,
        133,
        92,
        182,
        245,
        176,
        37
      ],
      "name": "feeApplied"
    },
    {
      "discriminator": [
        223,
        34,
        98,
        103,
        188,
        154,
        93,
        109
      ],
      "name": "feeScheduled"
    },
    {
      "discriminator": [
        176,
        119,
        42,
        75,
        95,
        125,
        169,
        176
      ],
      "name": "mintPauseChanged"
    },
    {
      "discriminator": [
        2,
        164,
        54,
        38,
        24,
        181,
        233,
        180
      ],
      "name": "seriesCreated"
    },
    {
      "discriminator": [
        131,
        204,
        47,
        197,
        56,
        43,
        110,
        179
      ],
      "name": "seriesFinalized"
    },
    {
      "discriminator": [
        134,
        220,
        152,
        208,
        56,
        170,
        13,
        171
      ],
      "name": "setMinted"
    },
    {
      "discriminator": [
        174,
        255,
        0,
        198,
        105,
        202,
        76,
        236
      ],
      "name": "setRedeemed"
    }
  ]
};
