#!/usr/bin/env python3
"""Builds idl/segments.json without the Anchor CLI.

Runs the same `__anchor_private_print_idl` tests that `anchor idl build` runs, then merges the
printed pieces (program, address, errors, events) and shortens `segments::module::Type` names
the way the CLI does. Usage: python3 scripts/build_idl.py
"""
import json
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "idl", "segments.json")
OUT_TS = os.path.join(ROOT, "idl", "segments.ts")


def chunks(text, kind):
    pattern = rf"--- IDL begin {kind} ---\n(.*?)\n--- IDL end {kind} ---"
    return [json.loads(m) for m in re.findall(pattern, text, re.S)]


def to_camel(s):
    """Port of Anchor TS `toCamelCase` (utils/case.ts)."""
    spaced = re.sub(r"[^A-Za-z0-9]+", " ", s)
    spaced = re.sub(r"([a-z][\d]*)([A-Z])", r"\1 \2", spaced)
    spaced = re.sub(r"([A-Z][A-Z\d]*)([A-Z][a-z])", r"\1 \2", spaced).strip()
    words = spaced.split()
    return "".join(w.lower() if i == 0 else w[:1].upper() + w[1:].lower() for i, w in enumerate(words))


def camel_idl(obj):
    """Port of Anchor TS `convertIdlToCamelCase`, which the generated types must match."""
    keys = {"name", "path", "account", "relations", "generic"}
    conv = lambda v: ".".join(to_camel(p) for p in v.split("."))
    if isinstance(obj, dict):
        return {k: ([conv(x) for x in v] if isinstance(v, list) else conv(v)) if k in keys and isinstance(v, (str, list))
                else camel_idl(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [camel_idl(x) for x in obj]
    return obj


def main():
    out = subprocess.run(
        ["cargo", "test", "-p", "segments", "--features", "idl-build", "--lib",
         "__anchor_private_print_idl", "--", "--show-output", "--quiet", "--test-threads=1"],
        cwd=ROOT, capture_output=True, text=True,
    )
    if out.returncode != 0:
        sys.stderr.write(out.stderr)
        sys.exit(out.returncode)
    text = out.stdout

    idl = chunks(text, "program")[0]
    address = chunks(text, "address")[0]
    idl["address"] = json.loads(address) if address.startswith('"') else address
    idl["errors"] = chunks(text, "errors")[0]

    types = {t["name"]: t for t in idl.get("types", [])}
    events = []
    for chunk in chunks(text, "event"):
        events.append(chunk["event"])
        for t in chunk.get("types", []):
            types.setdefault(t["name"], t)
    idl["events"] = sorted(events, key=lambda e: e["name"])
    idl["types"] = sorted(types.values(), key=lambda t: t["name"])

    short = {name: name.split("::")[-1] for name in types}
    assert len(set(short.values())) == len(short), "type name clash after shortening"
    raw = json.dumps(idl)
    for full, s in short.items():
        raw = raw.replace(f'"{full}"', f'"{s}"')
    idl = json.loads(raw)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(idl, f, indent=2)
        f.write("\n")
    # Same shape as the CLI's target/types file: the camelCased IDL as a TypeScript literal type.
    with open(OUT_TS, "w") as f:
        f.write("// Generated by scripts/build_idl.py. Do not edit.\n")
        f.write("export type Segments = ")
        json.dump(camel_idl(idl), f, indent=2)
        f.write(";\n")
    # The web app keeps its own copy so it builds without reaching outside app/.
    app_idl = os.path.join(ROOT, "app", "src", "idl")
    os.makedirs(app_idl, exist_ok=True)
    for src in (OUT, OUT_TS):
        with open(src) as f_in, open(os.path.join(app_idl, os.path.basename(src)), "w") as f_out:
            f_out.write(f_in.read())
    print(f"wrote {OUT}: {len(idl['instructions'])} instructions, {len(idl['events'])} events")


if __name__ == "__main__":
    main()
